Fix bug current page do not need to be clickable
kakeyang/Semantic-UI pull request #49
Opened 2018-07-09 07:50 UTC by namdhgc

2018-07-10 02:23 UTC, 4c0n approved these changes

2018-07-11 03:34 UTC, tuanhai2712 approved these changes

2018-07-11 03:37 UTC, jackdiff approved these changes

2018-07-11 03:37 UTC, jackdiff requested changes
Use more specific path

2018-07-11 04:27 UTC, jackdiff approved these changes

2018-07-11 04:38 UTC, merged