Add some style for marign
kakeyang/Semantic-UI pull request #58
Opened 2018-07-13 10:10 UTC by TaHieu-scuti

Add some style for marign

2018-07-13 10:27 UTC, namdhgc approved these changes

2018-07-16 03:13 UTC, jackdiff requested changes

2018-07-16 03:13 UTC, jackdiff commented on src/themes/irokoto-forts/collections/table.overrides
> +    .st-table_row td.st-table_row_column-user-campaign-title {
there is existing class  : word-break

2018-07-17 02:40 UTC, tuanhai2712 approved these changes

2018-07-17 02:47 UTC, jackdiff approved these changes

2018-07-17 02:56 UTC, 4c0n approved these changes

2018-07-17 02:57 UTC, merged