fix css for campaign report
kakeyang/Semantic-UI pull request #76
Opened 2018-07-23 05:57 UTC by tuanhai2712

2018-07-23 06:36 UTC, jackdiff approved these changes

2018-07-23 06:50 UTC, namdhgc approved these changes

2018-07-23 06:50 UTC, 4c0n requested changes

2018-07-23 06:50 UTC, 4c0n commented on src/themes/irokoto-forts/collections/form.overrides
> +    .st_radio_report:after {
Please use CSS3 syntax `::` instead of `:`.
https://developer.mozilla.org/en-US/docs/Web/CSS/::before

2018-07-23 06:50 UTC, 4c0n commented on src/themes/irokoto-forts/collections/form.overrides
> +    .st_radio_report:before {
Please use CSS3 syntax `::` instead of `:`.
https://developer.mozilla.org/en-US/docs/Web/CSS/::before

2018-07-23 09:37 UTC, TaHieu-scuti approved these changes

2018-07-24 02:52 UTC, 4c0n approved these changes

2018-07-24 03:42 UTC, merged